spring:
  cloud:
    config:
      server:
#        git:
#          uri: http://localhost/billjiang/spring-cloud-config.git
#          search-paths: config
#          username: billjiang
#          password: '{cipher}18a53c2c7157f17aa3d5a72dc77b4c31a023570c61186605efa3928ea4b343fd'

#Modified for Guiwang
        git:
          uri: http://10.27.213.70/Guiwang/sc-config-guiwang.git
#          uri: http://10.27.213.70/root/spring-cloud-config.git
          search-paths: config
          username: '{cipher}f97c33bcb6dcfc0e16cc1a243056762c93ca28e4ca25d13443a5292267f38daf'
          password: '{cipher}9d0efbda4a390e2b446da1f16cef7fe38b0515b96dbcd3ad65d133bded68edde'
          clone-on-start: true

security:
  basic:
    enabled: false
  user:
    name: user
    password: 123456
endpoints:
  bus:
    enabled: true
    sensitive: false



server:
  port: 8750

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}


---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: http://gitlab/billjiang/spring-cloud-config.git
          search-paths: config
          username: billjiang
          password: '{cipher}62291385f3566570dccf406c193d71953774554798eee423736da83cef4023e3'
server:
  port: ${{SERVER_PORT}:8750}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}
