spring:
  application:
    name: esp-registry
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: docker
server:
  port: ${{SERVER_PORT}:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,${ADDITIONAL_EUREKA_SERVER_LIST}

#Modified for Guiwang
---
spring:
  profiles: s-registry
eureka:
  instance:
    hostname: 0.0.0.0