server:
  port: 8081

spring:
  application:
    name: eap-admin
  security:
    user:
      ### The default UserDetailsService has a single user.
      ### The user name is user, and the password is random
      ### and is printed at INFO level when the application starts.
      password: 123456
      roles:
        - USER
        - ADMIN
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: mysql-admin
    url: jdbc:mysql://localhost:3306/eap-admin?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: mysql
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: ${environments.package.admin}.entity
  mapper-package: ${environments.package.admin}.mapper
  ### tk.mybatis.mapper.mapperhelper.MapperTemplate.getIDENTITY(tk.mybatis.mapper.entity.EntityColumn)
  ### 使用了MessageFormat.format(),需要用單引號轉義
  identity: SELECT REPLACE(UUID(), ''-'', '''')
  order: BEFORE
  wrap-keyword: '`{0}`'

logging:
  level:
    ### If you fine-tune your logging configuration, ensure that
    ### the org.springframework.boot.autoconfigure.security
    ### category is set to log INFO-level messages.
    ### Otherwise, the default password is not printed.
#    org.springframework.boot.autoconfigure.security: info
    com.amani.eap: DEBUG

environments:
  package:
    base: com.amani.eap
    admin: ${environments.package.base}.admin
  jwt:
    header: access-token
  swagger:
    service:
      title: Enterprise Application Platform
      description: An Enterprise Application Development Platform.
      developers: billJiang, 鬼王